swagger: '2.0'
info:
  title: Subflow UDP
  x-ibm-name: subflow-udp
  version: 1.0.0
  description: Description
  contact:
    name: Yaniv Yuzis
    email: YANIVS@il.ibm.com
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |
            var apim = require('apim');

            console.debug(apim.getvariable('local.parameter.message'));
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
basePath: /subflow-udp
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
  - {}
schemes:
  - https
x-udp:
  attach:
    - rest
    - soap
  gateways:
    - datapower-api-gateway
  properties:
    $schema: http://json-schema.org/draft-04/schema#
    type: object
    properties:
      message:
        label: Message
        type: string
        default: Hello UDP
    required:
      - message
